apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hackey
  labels:
    environment: production
  annotations:
    publisher: "http://127.0.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        environment: production
      annotations:
        publisher: "http://127.0.0.1"
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hackey
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: frontend
---


apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: builder
spec:
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      partition: 0  # Ensure rolling starts from 0
      maxUnavailable: 100%  # This allows all pods to be unavailable during updates
  replicas: 3  # Number of replicas for the StatefulSet
  # Other specifications for the StatefulSet
  template:
    metadata:
      labels:
        app: builder
    spec:
      containers:
      - name: builder-container
        image: your-image-here
---

version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always