apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: hackey
  labels:
    environment: production
  annotations:
    publisher: "http://127.0.0.1"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
        environment: production
      annotations:
        publisher: "http://127.0.0.1"
    spec:
      containers:
      - name: nginx
        image: nginx:stable
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: hackey
spec:
  type: NodePort
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 30080
  selector:
    app: frontend
